### PR TITLE
Implement Message Padding for Mixnet Commands

### PR DESCRIPTION
**Pull request by amitbasuri**
Issue: https://github.com/katzenpost/katzenpost/issues/371

This PR introduces uniform padding for all Noise protocol messages used in the mixnet, aligning them to the maximum size of the largest command, the Consensus command. The padding ensures that all messages serialize to the same size, preventing traffic analysis by obscuring the command types from passive network observers. The changes include modifications to the serialization functions for each command to apply zero-padding up to the specified maximum size, and unit tests have been added to verify that all commands meet the new size requirement.

### CODE REVIEW

**Comment by david415** [comment]
Very good start. I'm sorry I didn't explain all the details in the ticket. Here I will share more details.

The following commands are not sent over the mixnet, instead they are sent by mix nodes to the dirauths directly or they are sent among the dirauths:

GetVote
PostDescriptor
PostDescriptorStatus
Reveal
RevealStatus
Vote
VoteStatus
Cert
CertStatus
Sig
SigStatus

We do not need to pad the above set of commands.
We want to pad these commands:

GetConsensus
NoOp
Disconnect
SendPacket
RetrieveMessage
MessageACK
Message
MessageEmpty

The largest command among the above will be the Message command because it contains a Sphinx packet. The size of the sphinx packet depends on the configured Sphinx Geometry for that mixnet.

The unit test must check that the commands are serialized to the same size. Currently it's only checking that the padding are all zero bytes. It should check that the padding bytes are zero but you should use this helper function for that:

https://github.com/katzenpost/hpqc/blob/main/util/ctIsZero.go

**Comment by david415** [comment]
```
go test -v -run TestCommandVectors
=== RUN   TestCommandVectors
--- PASS: TestCommandVectors (0.00s)
PASS
ok  	github.com/katzenpost/katzenpost/core/wire/commands	0.002s
```

These tests should fail given that the test vectors were not updated.

**Comment by amitbasuri** [comment]
@david415 

1) For TestCommandVectors I am only asserting without the padding bytes `sendPacketBytes[:len(sendPacketCommand)]`
```go
	sendPacketBytes := sendPacket.ToBytes()
	assert.Equal(sendPacketBytes[:len(sendPacketCommand)], sendPacketCommand)
	assert.True(util.CtIsZero(sendPacketBytes[len(sendPacketCommand):]), "SendPacket: ToBytes() padding must be zero")
```

2) I passed `*geo.Geometry` to client to resolve `TestClient`

**Comment by david415** [comment]
> @david415
> 
>     1. For TestCommandVectors I am only asserting without the padding bytes `sendPacketBytes[:len(sendPacketCommand)]`
> 
> 
> ```go
> 	sendPacketBytes := sendPacket.ToBytes()
> 	assert.Equal(sendPacketBytes[:len(sendPacketCommand)], sendPacketCommand)
> 	assert.True(util.CtIsZero(sendPacketBytes[len(sendPacketCommand):]), "SendPacket: ToBytes() padding must be zero")
> ```
> 
>     2. I passed `*geo.Geometry` to client to resolve `TestClient`

All the integration tests are failing.

**Comment by david415** [comment]
Among the set of commands we want to pad:

GetConsensus
NoOp
Disconnect
SendPacket
RetrieveMessage
MessageACK
Message
MessageEmpty

I just now remembered that we have two directions. From client to server the `SendPacket` command is the biggest because it contains an entire Sphinx packet. What size is that? geo.PacketLength https://github.com/katzenpost/katzenpost/blob/main/core/sphinx/geo/geo.go#L44

But from server to client the biggest (discounting Consensus of course) is `Message` or `MessageAck`. However these are both smaller than `SendPacket` because they only contain part of the Sphinx payload (without the added SURB).

Therefore, we need two padding sizes... and two established lists of commands, egress vs ingress commands. The idea is that all the commands flowing from client to server will be padded to the same size, size A. And the commands flowing from server to client will be padded to size B.

**Comment by david415** [comment]
The `GetConsensus` command is a special case because we only want to pad it when it's sent over the mixnet. We don't want to pad it when sending to the dirauths.

**Review by david415 — APPROVED** [review]

**Pull request merged**
