### PR TITLE
add pyroscope continuous profiling

### PR DESCRIPTION
**Pull request by amitbasuri**

### CODE REVIEW

**Comment by ioerror** [comment]
@amitbasuri How can we help you to land this PR?

**Comment by amitbasuri** [comment]
@leif Please checkout https://github.com/0KnowledgeNetwork/devops/pull/64

**Comment by david415** [comment]
> @amitbasuri this looks very promising! can you tell me how to try it out?
> 
> perhaps you could add some instructions for using it to `./docker/README.rst`.

it looks like in order to use this feature we must build the mix server with the "pyroscope" build tag.
I can try to add that to the server/Makefile and I can merge main into this branch and get it ready to be merged...

**Comment by david415** [comment]
From looking at this changeset it seems we must at least document how to set these few environement variables:
`PYROSCOPE_SERVER_ADDRESS`
`PYROSCOPE_APP_NAME`
`PYROSCOPE_SERVICE_TAG`

**Comment by amitbasuri** [comment]
@david415 documentaion I will add, but are we sure that we want to configure using environment variables not with toml config, I did use environment variables for ease of use and test faster.

**Comment by david415** [comment]
> @david415 documentaion I will add, but are we sure that we want to configure using environment variables not with toml config, I did use environment variables for ease of use and test faster.

I merged main into this branch and I just now added a note at the bottom of root readme about building with profiling and pyroscope. Please edit the readme until you feel it is most accurate. Thank you!

**Comment by david415** [comment]
> @david415 documentaion I will add, but are we sure that we want to configure using environment variables not with toml config, I did use environment variables for ease of use and test faster.

I do not think we want this to be TOML configuration parameters because the feature is turned on and off with the build tags... so it's fine to use environment variables for this.

**Comment by david415** [comment]
> @amitbasuri this looks very promising! can you tell me how to try it out?
> 
> perhaps you could add some instructions for using it to `./docker/README.rst`.

I don't think we want CPU and memory profiling enabled for the docker mixnet... so i reverted the commit that did that. Also... in the spirit of fulfilling your request for documenting this feature, i've added a Pyroscope/pprof section to the root README which explains how to use this feature. It does provide useful details but also refers to the Pyroscope docs for setting up the pyroscope server which... as you must surely agree, is outside the scope of the Katzenpost README.

**Review by david415 — APPROVED** [review]
Looks very nice. Thanks for the contribution to Katzenpost!

**Pull request merged**
