### PR TITLE
Fix priority queue

### PR DESCRIPTION
**Pull request by david415**
This is a fix to the mixserver. This fixes:
https://github.com/katzenpost/katzenpost/issues/213

Also fixes:
https://github.com/katzenpost/katzenpost/issues/212

except that it doesn't allow for O(log n) deletion by priority... which currently is only needed by our buggy "client" package.

### CODE REVIEW

**Comment by david415** [comment]
> I do not agree that this is the right fix; rather that we should either update PriorityQueue to support adding entries with the same Priority or define the behavior of PriorityQueue to not support multiple items with the same Priority, and to return an error in that case. I think that the frequency this occurs is likely much lower than base packetloss rate and a nonissue. @Yawning might have an opinion we can consider as I suspect they considered this edge case when they wrote the PriorityQueue impl

I wrote the priority queue... not yawning.

**Comment by mixmasala** [comment]
> I do not agree that this is the right fix; rather that we should either update PriorityQueue to support adding entries with the same Priority or define the behavior of PriorityQueue to not support multiple items with the same Priority, and to return an error in that case. I think that the frequency this occurs is likely much lower than base packetloss rate and a nonissue. @Yawning might have an opinion we can consider as I suspect they considered this edge case when they wrote the PriorityQueue impl

per conversation with dawuud I'm more convinced that he is right and we should get rid of the extra complexity I added:

```
(because the mixserver should never remove a packet from the queue by a specific priority)
there is another way to fix the client as well
which is to just keep track of ACK'd messages
in a seperate datastructure, so that you dont need to remove them from the PriorityQueue
the thing I built that client uses is a single timer that is updated with the PriorityQueue, but if the timer fires and the thing is already ACK'd it's kinda OK to just check that it was ACK'd and not restransmit
and probably simplify that stuff as well
```

**Comment by mixmasala** [comment]
```
katzenpost# grep RemovePriority -r .
./client/timer_queue.go:			mo := a.priq.RemovePriority(priority)
./core/queue/priority_queue_test.go:		e := q.RemovePriority(v.Priority)
./core/queue/priority_queue_test.go:		e := q.RemovePriority(v.Priority)
./core/queue/priority_queue_test.go:	e := q.RemovePriority(1234)
./core/queue/priority_queue.go:// RemovePriority removes and returns element from the heap with given priority or nil
./core/queue/priority_queue.go:func (q *PriorityQueue) RemovePriority(priority uint64) interface{} {
```
It looks like there is only the client retransmission timer that makes use of RemovePriority, so the goal I think should be to revert the PriorityQueue and make TimerQueue keep track of acknowledgements - it does mean the timer fires for every message regardless if it was ACK'd or not but this should be a performance win overall .

**Comment by mixmasala** [comment]
@dawuud do you mind folding in changes I made in  #216 ?

**Pull request closed without merging**
