### PR TITLE
genconfig: default ratchet to CTIDH512-X25519

### PR DESCRIPTION
**Pull request by david415**

### CODE REVIEW

**Comment by ioerror** [comment]
This is related to #615

**Comment by ioerror** [comment]
If possible, it would be nice to have this test in parallel with the nobs csidh test - so we can see if one fails, if the other fails in the parallel run. I suspect the answer is that the nobs interface is somehow not as expected.

**Review by ioerror — CHANGES_REQUESTED** [review]
Could you please add a second test that tests the nobs usage in parallel to show that hpqc enables a functional catshadow with either parameter?

It seems that the hpqc nobs interface is not returning the same or similarly acceptable values as it used to return when the test previously passed.

**Comment by david415** [comment]
> Could you please add a second test that tests the nobs usage in parallel to show that hpqc enables a functional catshadow with either parameter?
> 
> It seems that the hpqc nobs interface is not returning the same or similarly acceptable values as it used to return when the test previously passed.

no. adding the second test is actually too much docker cpu time and it will take too long. we already run each test twice because of the push vs pull in the ci matrix. we can test the separately... like i'm doing now with the latest change to use the nobs csidh hybrid nike.

**Review by ioerror — APPROVED** [review]
Good enough for this iteration, thanks.

**Pull request merged**
