### PR TITLE
Add Streamlined NTRU Prime KEM

### PR DESCRIPTION
**Pull request by david415**

### CODE REVIEW

**Review by ioerror — APPROVED** [review]
Tests pass on power9:
```
$ go test -v
=== RUN   TestSNTRUPKEM
    sntrup_test.go:16: ciphertext size 1047
    sntrup_test.go:17: shared key size 32
    sntrup_test.go:18: private key size 1600
    sntrup_test.go:19: public key size 1218
    sntrup_test.go:20: seed size 32
    sntrup_test.go:21: encapsulation seed size 32
    sntrup_test.go:52: our shared key is 38c06c16eb4fba86627dd813203c2873313bd88885935ee67539a71533cf3de1
--- PASS: TestSNTRUPKEM (0.23s)
PASS
ok  	github.com/katzenpost/katzenpost/core/crypto/kem/sntrup	0.238s
```

The only downside is that we have an external dependency for an important security component that is in a repo that we don't control.

**Comment by ioerror** [comment]
I'd appreciate some KAT values in the test suite. Otherwise we should do a manual review of the upstream implementation to match with the reference implementation.

**Comment by david415** [comment]
> I'd appreciate some KAT values in the test suite. Otherwise we should do a manual review of the upstream implementation to match with the reference implementation.

we either add the KAT stuff upstream or nothing at all because we can't afford to maintain all the tests of this in the monorepo. i will not do it as it violates my organization scheme and principles.

**Comment by david415** [comment]
not merging this bullshit until we fork upstream sntrup

**Comment by david415** [comment]
> Tests pass on power9:
> 
> ```
> $ go test -v
> === RUN   TestSNTRUPKEM
>     sntrup_test.go:16: ciphertext size 1047
>     sntrup_test.go:17: shared key size 32
>     sntrup_test.go:18: private key size 1600
>     sntrup_test.go:19: public key size 1218
>     sntrup_test.go:20: seed size 32
>     sntrup_test.go:21: encapsulation seed size 32
>     sntrup_test.go:52: our shared key is 38c06c16eb4fba86627dd813203c2873313bd88885935ee67539a71533cf3de1
> --- PASS: TestSNTRUPKEM (0.23s)
> PASS
> ok  	github.com/katzenpost/katzenpost/core/crypto/kem/sntrup	0.238s
> ```
> 
> The only downside is that we have an external dependency for an important security component that is in a repo that we don't control.

we can pin our deps to specific git commit IDs or version tags to prevent the attack you are talking about.

**Comment by david415** [comment]
> I'd appreciate some KAT values in the test suite. Otherwise we should do a manual review of the upstream implementation to match with the reference implementation.

the KAT tests do not belong in the katzenpost monorepo. instead the appropriate place is our sntrup fork, here:

https://github.com/katzenpost/sntrup4591761

**Review by ioerror — APPROVED** [review]
Please ensure that https://github.com/katzenpost/sntrup4591761 builds before we import and merge this changeset.

**Comment by david415** [comment]
> Please ensure that https://github.com/katzenpost/sntrup4591761 builds before we import and merge this changeset.

i tested it manually. builds and passes it's own tests.

**Pull request merged**
