### PR TITLE
Fix ratchet

### PR DESCRIPTION
**Pull request by david415**

### CODE REVIEW

**Comment by ioerror** [comment]
What's up with #600? Do you think you guys could work together to fix things rather than competing requests with cherry-picking?

**Comment by david415** [comment]
> What's up with #600? Do you think you guys could work together to fix things rather than competing requests with cherry-picking?

in #600 they didn't bother to fix hpqc and thus selected a ratchet NIKE which doesn't work on all platforms?

**Comment by ioerror** [comment]
Please use highctidh v1.0.2024052900 - it was tagged just to solve your problem.

**Comment by david415** [comment]
> Please use highctidh v1.0.2024052900 - it was tagged just to solve your problem.

thanks! should be using that tag now.

**Comment by ioerror** [comment]
Please update this to use tag  v1.0.2024053000.

**Comment by ioerror** [comment]
To fix the CI, I think you'll want to close and reopen this pull request.

**Comment by ioerror** [comment]
In discussion with @david415; this will be closed (and a new PR opened) to try to shake the CI bug out.

**Pull request closed without merging**
