### PR TITLE
Fix 323 handle cborplugin failure

### PR DESCRIPTION
**Pull request by mixmasala**
This PR handles a kaetzchen plugin crash gracefully by unregistering it from the set of services.

### CODE REVIEW

**Comment by mixmasala** [comment]
I tested this by starting a dockerized mixnet and then killing one of the cbor plugin workers and verifying the provider node has not crashed.

```
06:27:28.286 DEBU scheduler: Batch processing 1 packets.
06:27:28.286 DEBU scheduler: Enqueueing packet: 1966 delta-t: 10ms
06:27:28.297 DEBU outgoing:1: Sent packet: 1966
06:27:28.324 DEBU outgoing:1: Sent packet: 1958
>>> 06:27:28.366 ERRO client: CBOR plugin worker, command exec error: signal: killed <<<
06:27:28.374 DEBU outgoing:1: Sent packet: 1962
06:27:28.536 DEBU incoming:1: Handing off packet: 1967
06:27:28.536 DEBU crypto:0: Packet: 1967 (Unwrap queue delay: 85.867µs)
06:27:28.536 DEBU crypto:0: Attempting to unwrap packet: 1967
06:27:28.537 DEBU crypto:0: Packet: 1967 (Unwrap took: 931.542µs)
06:27:28.537 DEBU crypto:0: Packet: 1967 (IsReplay took: 155.931µs)
```

However, in the next PKI, the descriptor still advertised the crashed service...

**Comment by mixmasala** [comment]
Oops. I called Wait() from inside a routine started by worker.Go().
I refactored this into a method unregister()

**Comment by mixmasala** [comment]
I've tested that this works by killing the service plugins and verifying that the service is no longer published in the PKI

**Review by threebithacker — APPROVED** [review]
Code looks fine to me, but if you think that the invariants you manually tested are important to preserve, perhaps we should add a CI test for that?

**Comment by mixmasala** [comment]
"Draft status because we don't know if this starts panic()ing all over"
This looks OK to merge to me. It shouldn't do anything if the code is correct, right  :)?

**Pull request merged**
