### PR TITLE
add CI testing matrix, make it work on Linux, Mac and Windows

### PR DESCRIPTION
**Pull request by david415**
Use github CI testing matrix for linux, mac and windows.
Make it compatible with windows by removing dependencies on CSIDH and using the generic NIKE ratchet instead.
Also no more memguard. Other than that I had to make a few of the unit tests into noops when the runtime detects windows. Oh and a cheap umask workaround helper function.

### CODE REVIEW

**Review by ioerror — CHANGES_REQUESTED** [review]
Please make the final check pass.

**Comment by david415** [comment]
> Please make the final check pass.

How!? It's a CI bug

**Review by ioerror — APPROVED** [review]

**Comment by david415** [comment]
per our discussion in the meeting please merge this pull request

**Comment by ioerror** [comment]
Okay merging this with the understanding that the delayed test is a hiccup.

**Pull request merged**
